name: CI Checks & Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "CI Performance"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Add dist bundle
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "halison700@gmail.com"
          git config --local user.name "GitHub Actions"
          git add --force dist
          git commit -m "CI automation $(date)"
      - name: Push changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/performance.js
          flags: --out json=results.json

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json    
